-- create_tables.sql

DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    APELLIDO VARCHAR(30) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    MATRICULA VARCHAR(50) NOT NULL
);